// client-vue/src/components/Loading.vue
<template>
  <div class="loading-container">
    <h2 class="loading-text">Loading</h2>
    <img class="loading-image" src="../assets/images/loading.gif" alt="Loading..." />
  </div>
</template>

<script>
export default {
  name: "Loading",
};
</script>

<style scoped>
.loading-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 200px;
  padding: 20px;
}

.loading-text {
  color: black;
  font-size: 2em;
  margin-bottom: 20px;
  font-family: "VT323", monospace;
}

.loading-image {
  width: 35%;
  height: auto;
}
</style>

// client/src/components/loading/Loading.jsx
import React from "react";
import styles from "./Loading.module.css";
import loaderGif from "../../assets/images/loading.gif";

const Loading = () => {
  return (
    <div style={{ textAlign: "center", marginTop: "20px" }}>
      <h2 style={{ color: "black" }}> Loading </h2>
      <img className={styles.image} src={loaderGif} alt="Loading..." />
    </div>
  );
};

export default Loading;
